In [1]:
import numpy as np 
import pandas as pd

In [2]:
movie=pd.read_csv('tmdb_5000_movies.csv')
credit=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movie.sample(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1790,26000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,134,"[{""id"": 530, ""name"": ""prophecy""}, {""id"": 531, ...",en,"O Brother, Where Art Thou?","In the deep south during the 1930s, three esca...",39.742009,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...",2000-08-30,71868327,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They have a plan...but not a clue.,"O Brother, Where Art Thou?",7.3,1112

In [4]:
credit.sample(2)

,movie_id,title,cast,crew
801,1813,The Devil's Advocate,"[{""cast_id"": 1, ""character"": ""Kevin Lomax"", ""c...","[{""credit_id"": ""53e14bf30e0a264ea600001d"", ""de..."
880,285923,Grindhouse,"[{""cast_id"": 3, ""character"": ""Stuntman Mike (s...","[{""credit_id"": ""54004dc7c3a3684372001354"", ""de..."

In [5]:
df=movie.merge(credit,on='title')

In [6]:
df.sample(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
1412,35000000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 9648, ""n...",NaN,13515,"[{""id"": 222, ""name"": ""schizophrenia""}, {""id"": ...",en,Mirrors,An ex-cop and his family are the target of an ...,19.774543,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...",...,110.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There is evil...On the other side.,Mirrors,6.0,485,13515,"[{""cast_id"": 6, ""character"": ""Ben Carson"", ""cr...","[{""credit_id"": ""53562d380e0a26285e002d7c"", ""de..."

In [7]:
# columns that we keep in our dataset
# generes 
# id
# keyword 
# overview
# cast
#crew
df=df[['id','genres','keywords','overview','cast','crew']]

In [8]:
df.sample(1)

,id,genres,keywords,overview,cast,crew
744,137106,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 16, ""...","[{""id"": 494, ""name"": ""father son relationship""...","An ordinary Lego mini-figure, mistakenly thoug...","[{""cast_id"": 16, ""character"": ""Emmet Brickowsk...","[{""credit_id"": ""53a44a6cc3a3682a4200128a"", ""de..."

In [9]:
df.isnull().sum()

id          0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
import ast 
def converter(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [13]:
df['genres']=df['genres'].apply(converter)

In [14]:
df.head(1)

,id,genres,keywords,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [15]:
df['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [16]:
df['keywords']=df['keywords'].apply(converter)

In [17]:
df.head(1)

,id,genres,keywords,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
df['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [19]:
def converter2(obj):
    l=[]
    count=0
    for i in  ast.literal_eval(obj):
        if count<=3:
           l.append(i['name'])
           count+=1
        else:
            break
    return l

In [20]:
df['cast']=df['cast'].apply(converter2)

In [21]:
df.head(1)

,id,genres,keywords,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [22]:
df['cast'][0]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang']

In [23]:
df['crew'][2]

'[{"credit_id": "54805967c3a36829b5002c41", "department": "Sound", "gender": 2, "id": 153, "job": "Original Music Composer", "name": "Thomas Newman"}, {"credit_id": "52fe4d22c3a368484e1d8d77", "department": "Directing", "gender": 2, "id": 39, "job": "Director", "name": "Sam Mendes"}, {"credit_id": "5677cd99925141691a005333", "department": "Art", "gender": 1, "id": 8384, "job": "Set Decoration", "name": "Anna Pinnock"}, {"credit_id": "52fe4d22c3a368484e1d8d8d", "department": "Writing", "gender": 2, "id": 932, "job": "Screenplay", "name": "John Logan"}, {"credit_id": "562fc9bb92514129fe0006b4", "department": "Writing", "gender": 2, "id": 932, "job": "Story", "name": "John Logan"}, {"credit_id": "5654d41c92514145c3000373", "department": "Art", "gender": 2, "id": 4248, "job": "Production Design", "name": "Dennis Gassner"}, {"credit_id": "52fe4d22c3a368484e1d8d71", "department": "Writing", "gender": 2, "id": 9856, "job": "Characters", "name": "Ian Fleming"}, {"credit_id": "54805989c3a36829ae0022d8", "department": "Editing", "gender": 0, "id": 3904, "job": "Editor", "name": "Lee Smith"}, {"credit_id": "5677df82c3a3681683008748", "department": "Sound", "gender": 2, "id": 7538, "job": "Music Editor", "name": "Bill Bernstein"}, {"credit_id": "5720e370c3a368117e00045b", "department": "Production", "gender": 2, "id": 8784, "job": "Co-Producer", "name": "Daniel Craig"}, {"credit_id": "5522fdd09251416d4a0024b6", "department": "Costume & Make-Up", "gender": 1, "id": 11227, "job": "Costume Design", "name": "Jany Temime"}, {"credit_id": "5677cc9ac3a368167c0089b5", "department": "Production", "gender": 1, "id": 10496, "job": "Casting", "name": "Debbie McWilliams"}, {"credit_id": "52fe4d22c3a368484e1d8d7d", "department": "Production", "gender": 1, "id": 10666, "job": "Producer", "name": "Barbara Broccoli"}, {"credit_id": "5720e3afc3a368117e00046a", "department": "Production", "gender": 0, "id": 11268, "job": "Line Producer", "name": "Roberto Malerba"}, {"credit_id": "5677df58c3a368167c008c82", "department": "Sound", "gender": 0, "id": 40827, "job": "Music Editor", "name": "Peter Clarke"}, {"credit_id": "5677dd1ec3a36816890085d3", "department": "Sound", "gender": 0, "id": 14764, "job": "Sound Designer", "name": "Christopher Assells"}, {"credit_id": "566046b9c3a36875f400323a", "department": "Sound", "gender": 0, "id": 14765, "job": "Supervising Sound Editor", "name": "Per Hallberg"}, {"credit_id": "5677ccab925141691a00530f", "department": "Production", "gender": 0, "id": 36108, "job": "Casting", "name": "Nicole Schmied"}, {"credit_id": "5677cfe4c3a36816850087d2", "department": "Production", "gender": 0, "id": 36108, "job": "Casting Associate", "name": "Nicole Schmied"}, {"credit_id": "562fc984c3a3681b5400e16f", "department": "Writing", "gender": 2, "id": 10783, "job": "Screenplay", "name": "Robert Wade"}, {"credit_id": "562fc9cec3a3681b4b00d168", "department": "Writing", "gender": 2, "id": 10783, "job": "Story", "name": "Robert Wade"}, {"credit_id": "562fc976c3a3681b5c00dd64", "department": "Writing", "gender": 0, "id": 10782, "job": "Screenplay", "name": "Neal Purvis"}, {"credit_id": "562fc9d79251414ad800c103", "department": "Writing", "gender": 0, "id": 10782, "job": "Story", "name": "Neal Purvis"}, {"credit_id": "5720e61d9251414235000477", "department": "Production", "gender": 2, "id": 10876, "job": "Executive Producer", "name": "Callum McDougall"}, {"credit_id": "562fc9a89251414ad800c0fe", "department": "Writing", "gender": 2, "id": 21339, "job": "Screenplay", "name": "Jez Butterworth"}, {"credit_id": "570bd7f2c3a36802a9000412", "department": "Art", "gender": 0, "id": 23425, "job": "Supervising Art Director", "name": "Chris Lowe"}, {"credit_id": "5677e45ac3a368168b0084fd", "department": "Art", "gender": 0, "id": 23491, "job": "Assistant Art Director", "name": "Roxana Alexandru "}, {"credit_id": "5677e29c925141691a00561c", "department": "Crew", "gender": 0, "id": 23774, "job": "Makeup Effects", "name": "Jo Grover"}, {"credit_id": "5677cf8492514179d20088ae", "department": "Production", "gender": 2, "id": 10907, "job": "Casting", "name": "St\\u00e9phane Foenkinos"}, {"credit_id": "5677d7b192514179d20089c6", "department": "Camera", "gender": 2, "id": 61851, "job": "Camera Operator", "name": "Lorenzo Senatore"}, {"credit_id": "5720e6f7925141423000046b", "department": "Production", "gender": 0, "id": 64000, "job": "Line Producer", "name": "Wolfgang Ramml"}, {"credit_id": "5677dfabc3a368168000899f", "department": "Sound", "gender": 2, "id": 66941, "job": "Orchestrator", "name": "J.A.C. Redford"}, {"credit_id": "5720e72e92514142320007fc", "department": "Production", "gender": 0, "id": 81517, "job": "Associate Producer", "name": "Gregg Wilson"}, {"credit_id": "52fe4d22c3a368484e1d8d83", "department": "Production", "gender": 2, "id": 69678, "job": "Producer", "name": "Michael G. Wilson"}, {"credit_id": "5720e325c3a368118100043e", "department": "Production", "gender": 0, "id": 77511, "job": "Line Producer", "name": "Zakaria Alaoui"}, {"credit_id": "548059799251416e7e00265c", "department": "Camera", "gender": 0, "id": 74401, "job": "Director of Photography", "name": "Hoyte van Hoytema"}, {"credit_id": "5677cef792514179db00904d", "department": "Crew", "gender": 0, "id": 239885, "job": "Special Effects Coordinator", "name": "Franco Ragusa"}, {"credit_id": "5677d7e992514179e7008654", "department": "Camera", "gender": 0, "id": 937946, "job": "Camera Operator", "name": "Peter Field"}, {"credit_id": "5677cd21c3a3681680008700", "department": "Art", "gender": 2, "id": 979698, "job": "Art Direction", "name": "Neal Callow"}, {"credit_id": "5677cd5a92514179e30086fb", "department": "Art", "gender": 2, "id": 986687, "job": "Art Direction", "name": "Mark Harris"}, {"credit_id": "5678090392514179e1009958", "department": "Crew", "gender": 0, "id": 1024842, "job": "Visual Effects Editor", "name": "Billy A. Campbell"}, {"credit_id": "5720e6749251414240000470", "department": "Production", "gender": 0, "id": 1026247, "job": "Co-Producer", "name": "Stacy Perskie"}, {"credit_id": "56780a2292514179dd008d18", "department": "Visual Effects", "gender": 0, "id": 1029804, "job": "Visual Effects Producer", "name": "Laura Schultz"}, {"credit_id": "5677e174925141691a0055f1", "department": "Costume & Make-Up", "gender": 0, "id": 1087452, "job": "Key Hair Stylist", "name": "Mari Paz Robles"}, {"credit_id": "5677e0cf9251417845001631", "department": "Costume & Make-Up", "gender": 0, "id": 1099281, "job": "Hairstylist", "name": "Gerardo Perez Arreola"}, {"credit_id": "5677d73b92514179dd008471", "department": "Camera", "gender": 0, "id": 1118711, "job": "Camera Operator", "name": "Kenji Katori"}, {"credit_id": "5677cd3a92514179d2008852", "department": "Art", "gender": 0, "id": 1296445, "job": "Art Direction", "name": "Ben Collins"}, {"credit_id": "5677cfc3c3a3681680008755", "department": "Production", "gender": 0, "id": 1305251, "job": "Casting Associate", "name": "Tusse Lande"}, {"credit_id": "5677e24f92514179e70087da", "department": "Costume & Make-Up", "gender": 0, "id": 1315700, "job": "Makeup Artist", "name": "Donald Mowat"}, {"credit_id": "5677d622c3a368167c008b25", "department": "Costume & Make-Up", "gender": 0, "id": 1319160, "job": "Costume Supervisor", "name": "Ken Crouch"}, {"credit_id": "5677cd0ec3a368168e008f75", "department": "Art", "gender": 0, "id": 1335539, "job": "Art Direction", "name": "Andrew Bennett"}, {"credit_id": "56780833925141691a005c2f", "department": "Visual Effects", "gender": 0, "id": 1338241, "job": "Visual Effects Coordinator", "name": "Sean McGrath"}, {"credit_id": "5677dcc7c3a36816830086cc", "department": "Sound", "gender": 0, "id": 1338372, "job": "Foley", "name": "Dan O\'Connell"}, {"credit_id": "56780ac692514179dd008d31", "department": "Visual Effects", "gender": 0, "id": 1341741, "job": "Visual Effects Supervisor", "name": "Mark Curtis"}, {"credit_id": "5677dd9fc3a368168b0083f0", "department": "Sound", "gender": 2, "id": 1341858, "job": "Sound Re-Recording Mixer", "name": "Gregg Rudloff"}, {"credit_id": "566047029251412204002337", "department": "Directing", "gender": 0, "id": 1342669, "job": "Script Supervisor", "name": "Jayne-Ann Tenggren"}, {"credit_id": "5720e713925141423000046d", "department": "Production", "gender": 0, "id": 1342669, "job": "Associate Producer", "name": "Jayne-Ann Tenggren"}, {"credit_id": "5677dd8792514179db009235", "department": "Sound", "gender": 0, "id": 1345595, "job": "Sound Re-Recording Mixer", "name": "Scott Millan"}, {"credit_id": "5677def192514179e700875b", "department": "Directing", "gender": 0, "id": 1358025, "job": "Script Supervisor", "name": "Nicoletta Mani"}, {"credit_id": "5677dcb0925141691a00552a", "department": "Sound", "gender": 0, "id": 1367493, "job": "Foley", "name": "John T. Cucci"}, {"credit_id": "5677d7ff92514179e300884b", "department": "Camera", "gender": 0, "id": 1377503, "job": "Camera Operator", "name": "Sebastian Meuschel"}, {"credit_id": "5677d94192514179d20089ff", "department": "Camera", "gender": 2, "id": 1388897, "job": "Steadicam Operator", "name": "Julian Morson"}, {"credit_id": "5677dce5c3a36816830086d3", "department": "Sound", "gender": 0, "id": 1389614, "job": "Foley", "name": "Peter Michael Sullivan"}, {"credit_id": "56780a5a92514179e300908d", "department": "Visual Effects", "gender": 0, "id": 1391691, "job": "Visual Effects Producer", "name": "Ken Dailey"}, {"credit_id": "5677dd38c3a368167c008c21", "department": "Sound", "gender": 0, "id": 1392083, "job": "Sound Designer", "name": "Ann Scibelli"}, {"credit_id": "5677d7cd92514179db009178", "department": "Camera", "gender": 0, "id": 1392246, "job": "Camera Operator", "name": "Clive Jackson"}, {"credit_id": "5677de6192514179dd008566", "department": "Directing", "gender": 0, "id": 1392661, "job": "Script Supervisor", "name": "Susie Jones"}, {"credit_id": "5677d98fc3a3681685008904", "department": "Camera", "gender": 2, "id": 1392718, "job": "Still Photographer", "name": "Jasin Boland"}, {"credit_id": "5677cdd8c3a368168b0081e1", "department": "Art", "gender": 0, "id": 1394117, "job": "Art Department Coordinator", "name": "Jennifer Lewicki"}, {"credit_id": "5677e58cc3a3681685008adb", "department": "Art", "gender": 0, "id": 1398089, "job": "Greensman", "name": "Ian Whiteford"}, {"credit_id": "56780a7592514179db0099c4", "department": "Visual Effects", "gender": 0, "id": 1398100, "job": "Visual Effects Producer", "name": "Kilou Picard"}, {"credit_id": "5677d8ba92514179d20089f0", "department": "Camera", "gender": 0, "id": 1399071, "job": "Helicopter Camera", "name": "Hans Bjerno"}, {"credit_id": "5677dd02c3a368167a0091a2", "department": "Editing", "gender": 2, "id": 1399862, "job": "Dialogue Editor", "name": "Daniel Saxlid"}, {"credit_id": "5677e2e1c3a368167c008d1a", "department": "Costume & Make-Up", "gender": 0, "id": 1401126, "job": "Wigmaker", "name": "Alex Rouse"}, {"credit_id": "5678096bc3a368167c0093d2", "department": "Crew", "gender": 0, "id": 1401147, "job": "Visual Effects Editor", "name": "Anik Seguin"}, {"credit_id": "5677dc90c3a368167a009190", "department": "Sound", "gender": 0, "id": 1401631, "job": "ADR & Dubbing", "name": "Michelle Pazer"}, {"credit_id": "5677d75ac3a368167a0090e9", "department": "Camera", "gender": 2, "id": 1403411, "job": "Camera Operator", "name": "Lucas Bielan"}, {"credit_id": "566046d7c3a36875e900359d", "department": "Sound", "gender": 0, "id": 1404212, "job": "Supervising Sound Editor", "name": "Karen Baker Landers"}, {"credit_id": "5677dd519251417845001588", "department": "Sound", "gender": 0, "id": 1404217, "job": "Sound Designer", "name": "Peter Staubli"}, {"credit_id": "5677d8d192514179e1009100", "department": "Camera", "gender": 0, "id": 1404244, "job": "Helicopter Camera", "name": "John Marzano"}, {"credit_id": "5677d927c3a36816850088f2", "department": "Camera", "gender": 0, "id": 1405241, "job": "Helicopter Camera", "name": "Adam Dale"}, {"credit_id": "5677dff292514179e100921a", "department": "Editing", "gender": 0, "id": 1408363, "job": "First Assistant Editor", "name": "Emma McCleave"}, {"credit_id": "5677e191925141784500164f", "department": "Costume & Make-Up", "gender": 0, "id": 1409821, "job": "Makeup Designer", "name": "Naomi Donne"}, {"credit_id": "5677e2b5c3a368168e0092aa", "department": "Crew", "gender": 0, "id": 1411323, "job": "Makeup Effects", "name": "Susan Howard"}, {"credit_id": "5677d869c3a36816850088e3", "department": "Lighting", "gender": 0, "id": 1414096, "job": "Gaffer", "name": "David Smith"}, {"credit_id": "56780712c3a368168b008ace", "department": "Crew", "gender": 0, "id": 1415157, "job": "CG Supervisor", "name": "Joel Green"}, {"credit_id": "567806ba92514179e10098ee", "department": "Crew", "gender": 0, "id": 1425484, "job": "CG Supervisor", "name": "Laurent Hugueniot"}, {"credit_id": "56780a92c3a36816850090af", "department": "Visual Effects", "gender": 0, "id": 1425488, "job": "Visual Effects Producer", "name": "Tim Keene"}, {"credit_id": "5677e087c3a368167a00922b", "department": "Costume & Make-Up", "gender": 0, "id": 1425971, "job": "Hair Designer", "name": "Zoe Tahir"}, {"credit_id": "567808eb92514179e300904a", "department": "Crew", "gender": 0, "id": 1428902, "job": "Visual Effects Editor", "name": "Conor Byrne"}, {"credit_id": "5677e22d925141691a00560d", "department": "Costume & Make-Up", "gender": 0, "id": 1439128, "job": "Makeup Artist", "name": "Charlotte Hayward"}, {"credit_id": "5677cf3fc3a36816850087c1", "department": "Visual Effects", "gender": 0, "id": 1442137, "job": "Animation Supervisor", "name": "Catherine Mullan"}, {"credit_id": "56780988c3a3681683008e99", "department": "Crew", "gender": 0, "id": 1447617, "job": "Visual Effects Editor", "name": "Crystal Hadcroft"}, {"credit_id": "5677e0ec925141691a0055d6", "department": "Costume & Make-Up", "gender": 0, "id": 1458416, "job": "Hairstylist", "name": "Francesca Crowder"}, {"credit_id": "5677cf2892514179dd008356", "department": "Visual Effects", "gender": 0, "id": 1459878, "job": "Animation Director", "name": "Marlene Chazot"}, {"credit_id": "5678091d92514179db009985", "department": "Crew", "gender": 0, "id": 1459899, "job": "Visual Effects Editor", "name": "Struan Farquhar"}, {"credit_id": "56780731c3a3681680009013", "department": "Crew", "gender": 0, "id": 1459925, "job": "CG Supervisor", "name": "Daniel Pastore"}, {"credit_id": "5677d969c3a368168b00834a", "department": "Camera", "gender": 0, "id": 1470167, "job": "Still Photographer", "name": "Jonathan Olley"}, {"credit_id": "5677e48dc3a368167a0092c8", "department": "Art", "gender": 0, "id": 1472773, "job": "Assistant Art Director", "name": "Sami Gaidi"}, {"credit_id": "5751eed59251416b60000637", "department": "Production", "gender": 2, "id": 1477203, "job": "Co-Producer", "name": "Luca Marco Paracels"}, {"credit_id": "5677e157c3a36816800089ee", "department": "Costume & Make-Up", "gender": 0, "id": 1480629, "job": "Key Hair Stylist", "name": "Luca Vannella"}, {"credit_id": "56780b0e925141691a005c8f", "department": "Visual Effects", "gender": 0, "id": 1483141, "job": "Visual Effects Supervisor", "name": "Stuart Bullen"}, {"credit_id": "582f29fa925141022e003a74", "department": "Sound", "gender": 0, "id": 1494824, "job": "Sound Effects Editor", "name": "Russell Edwards"}, {"credit_id": "5677d63dc3a368167a0090b4", "department": "Costume & Make-Up", "gender": 0, "id": 1510431, "job": "Costume Supervisor", "name": "Stefano De Nardis"}, {"credit_id": "5677d79992514179d20089c2", "department": "Camera", "gender": 0, "id": 1512767, "job": "Camera Operator", "name": "Luis David Sansans"}, {"credit_id": "5677d609c3a368168000881a", "department": "Costume & Make-Up", "gender": 0, "id": 1545912, "job": "Costume Supervisor", "name": "Abderrahim Benkhayi"}, {"credit_id": "5677d66cc3a368167a0090be", "department": "Costume & Make-Up", "gender": 0, "id": 1545913, "job": "Set Costumer", "name": "Rachid Aadassi"}, {"credit_id": "5677da26c3a368167a009139", "department": "Camera", "gender": 0, "id": 1545995, "job": "Additional Camera", "name": "Carlos De Carvalho"}, {"credit_id": "5677d5bec3a368167c008b13", "department": "Costume & Make-Up", "gender": 0, "id": 1546747, "job": "Assistant Costume Designer", "name": "Vivienne Jones"}, {"credit_id": "5677dfcac3a368168300875b", "department": "Editing", "gender": 0, "id": 1548406, "job": "Digital Intermediate", "name": "Kim Honeyman"}, {"credit_id": "5677e105c3a368168b00846d", "department": "Costume & Make-Up", "gender": 0, "id": 1550637, "job": "Hairstylist", "name": "Kathryn Fa"}, {"credit_id": "5677ce0c9251417845001384", "department": "Crew", "gender": 0, "id": 1551770, "job": "Carpenter", "name": "Paul Duff"}, {"credit_id": "5677ce5192514179e300871b", "department": "Crew", "gender": 0, "id": 1551771, "job": "Property Master", "name": "Ben Wilkinson"}, {"credit_id": "5677cec292514179dd00834d", "department": "Crew", "gender": 0, "id": 1551772, "job": "Special Effects Coordinator", "name": "Lynne Corbould"}, {"credit_id": "5677cf57c3a368168e008fcc", "department": "Production", "gender": 0, "id": 1551773, "job": "Casting", "name": "Amal El-Farfachi"}, {"credit_id": "5677cf99c3a368168b00821d", "department": "Production", "gender": 0, "id": 1551774, "job": "Casting Associate", "name": "Celebrity Booker"}, {"credit_id": "5677cfadc3a368167c008a30", "department": "Production", "gender": 0, "id": 1551775, "job": "Casting Associate", "name": "Lucy Hellier"}, {"credit_id": "5677d5a392514179db00911d", "department": "Costume & Make-Up", "gender": 0, "id": 1551777, "job": "Assistant Costume Designer", "name": "Richard Davies"}, {"credit_id": "5677dd6bc3a368168b0083e2", "department": "Sound", "gender": 0, "id": 1551789, "job": "Sound Effects Editor", "name": "Ando Johnson"}, {"credit_id": "5677de2dc3a3681683008713", "department": "Crew", "gender": 0, "id": 1551791, "job": "Armorer", "name": "Greg Corke"}, {"credit_id": "5677de8a92514179e10091d9", "department": "Production", "gender": 0, "id": 1551796, "job": "Researcher", "name": "Amin Rharda"}, {"credit_id": "5677dea9c3a368168e00921c", "department": "Crew", "gender": 0, "id": 1551797, "job": "Armorer", "name": "Joss Skottowe"}, {"credit_id": "5677e11c92514179dd0085e3", "department": "Costume & Make-Up", "gender": 0, "id": 1551798, "job": "Hairstylist", "name": "Joseph Koniak"}, {"credit_id": "5677e1b19251417845001657", "department": "Costume & Make-Up", "gender": 0, "id": 1551800, "job": "Makeup Artist", "name": "Thal\\u00eda Echeveste"}, {"credit_id": "5677e1c7c3a368167c008cd8", "department": "Costume & Make-Up", "gender": 0, "id": 1551801, "job": "Makeup Artist", "name": "Charlie Hounslow"}, {"credit_id": "5677e1e592514179d2008b7b", "department": "Costume & Make-Up", "gender": 0, "id": 1551802, "job": "Makeup Artist", "name": "Lucy Friend"}, {"credit_id": "5677e1fa92514179e1009265", "department": "Costume & Make-Up", "gender": 0, "id": 1551803, "job": "Makeup Artist", "name": "Yelska Labrada"}, {"credit_id": "5677e20fc3a36816830087d9", "department": "Costume & Make-Up", "gender": 0, "id": 1551804, "job": "Makeup Artist", "name": "Ana Gabriela Quinonez"}, {"credit_id": "5677e32d9251417845001683", "department": "Production", "gender": 0, "id": 1551807, "job": "Researcher", "name": "Gina De Ferrer"}, {"credit_id": "5677e47592514179e10092dd", "department": "Art", "gender": 0, "id": 1551809, "job": "Assistant Art Director", "name": "Lydia Fry"}, {"credit_id": "5677e4a492514179db009373", "department": "Art", "gender": 0, "id": 1551810, "job": "Assistant Art Director", "name": "Liam Georgensen"}, {"credit_id": "5677e4bb92514179dd00868a", "department": "Art", "gender": 0, "id": 1551811, "job": "Assistant Art Director", "name": "Hugh McClelland"}, {"credit_id": "5677e53092514179db00938e", "department": "Crew", "gender": 0, "id": 1551812, "job": "Carpenter", "name": "John Allen"}, {"credit_id": "5677e547c3a368167a0092ef", "department": "Crew", "gender": 0, "id": 1551813, "job": "Carpenter", "name": "Eddie Murphy"}, {"credit_id": "567806e092514179dd008c84", "department": "Crew", "gender": 0, "id": 155

In [24]:
def converter3(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=="Director":
            l.append(i['name'])
            break
    return l

In [25]:
df['crew']=df['crew'].apply(converter3)

In [26]:
df.head(1)

,id,genres,keywords,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]

In [27]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [28]:
df.head(5)

,id,genres,keywords,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [29]:
# romoving extra spaces
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df['crew']=df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
df.head()

,id,genres,keywords,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [31]:
df['tag']=df['genres'] + df['keywords'] + df['overview'] + df['cast'] + df['crew']

In [32]:
df.head(1)

,id,genres,keywords,overview,cast,crew,tag
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."

In [33]:
new_df=df[['id','tag']]

In [34]:
new_df.head(2)

      id                                                tag
0  19995  [Action, Adventure, Fantasy, ScienceFiction, c...
1    285  [Adventure, Fantasy, Action, ocean, drugabuse,...

In [35]:
new_df['title']=movie['title']

C:\Users\HP\AppData\Local\Temp\ipykernel_24144\800980742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title']=movie['title']

In [36]:
new_df

,id,tag,title
0,19995,"[Action, Adventure, Fantasy, ScienceFiction, c...",Avatar
1,285,"[Adventure, Fantasy, Action, ocean, drugabuse,...",Pirates of the Caribbean: At World's End
2,206647,"[Action, Adventure, Crime, spy, basedonnovel, ...",Spectre
3,49026,"[Action, Crime, Drama, Thriller, dccomics, cri...",The Dark Knight Rises
4,49529,"[Action, Adventure, ScienceFiction, basedonnov...",John Carter
...,...,...,...
4804,9367,"[Action, Crime, Thriller, unitedstates–mexicob...",NaN
4805,72766,"[Comedy, Romance, A, newlywed, couple's, honey...",NaN
4806,231617,"[Comedy, Drama, Romance, TVMovie, date, loveat...",NaN
4807,126186,"[When, ambitious, New, York, attorney, Sam, is...",NaN
4808,25975,"[Documentary, obsession, camcorder, crush, dre...",NaN

In [37]:
new_df.isnull().sum()

id       0
tag      0
title    6
dtype: int64

In [38]:
new_df.dropna(inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24144\1925939579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.dropna(inplace=True)

In [39]:
new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_24144\4079141722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

In [40]:
new_df

,id,tag,title
0,19995,Action Adventure Fantasy ScienceFiction cultur...,Avatar
1,285,Adventure Fantasy Action ocean drugabuse exoti...,Pirates of the Caribbean: At World's End
2,206647,Action Adventure Crime spy basedonnovel secret...,Spectre
3,49026,Action Crime Drama Thriller dccomics crimefigh...,The Dark Knight Rises
4,49529,Action Adventure ScienceFiction basedonnovel m...,John Carter
...,...,...,...
4798,36095,Crime Horror Mystery Thriller japan prostitute...,El Mariachi
4799,182291,Drama confession hazing gangmember latino lgbt...,Newlyweds
4800,286939,Thriller Horror Comedy It should have been jus...,"Signed, Sealed, Delivered"
4801,124606,Drama gang audition policefake homeless actres...,Shanghai Calling
4802,14337,ScienceFiction Drama Thriller distrust garage ...,My Date with Drew

In [41]:
new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_24144\1740795540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

In [42]:
new_df

,id,tag,title
0,19995,action adventure fantasy sciencefiction cultur...,Avatar
1,285,adventure fantasy action ocean drugabuse exoti...,Pirates of the Caribbean: At World's End
2,206647,action adventure crime spy basedonnovel secret...,Spectre
3,49026,action crime drama thriller dccomics crimefigh...,The Dark Knight Rises
4,49529,action adventure sciencefiction basedonnovel m...,John Carter
...,...,...,...
4798,36095,crime horror mystery thriller japan prostitute...,El Mariachi
4799,182291,drama confession hazing gangmember latino lgbt...,Newlyweds
4800,286939,thriller horror comedy it should have been jus...,"Signed, Sealed, Delivered"
4801,124606,drama gang audition policefake homeless actres...,Shanghai Calling
4802,14337,sciencefiction drama thriller distrust garage ...,My Date with Drew

In [43]:
# steamming 
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [44]:
def stem(text):
    l=[]
    for i in text.split():
        l.append(ps.stem(i))
    return " ".join(l)

In [45]:
new_df['tag']=new_df['tag'].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_24144\599176683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(stem)

In [46]:
new_df['tag'][0]

'action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. samworthington zoesaldana sigourneyweav stephenlang jamescameron'

In [47]:
# vectorization 
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [48]:
vector=cv.fit_transform(new_df['tag']).toarray()

In [49]:
vector.shape

(4800, 5000)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity_score=cosine_similarity(vector)

In [52]:
similarity_score[2]

array([0.08703883, 0.05884899, 1.        , ..., 0.        , 0.        ,
       0.        ], shape=(4800,))

In [53]:
def recommend(movie):
    index=new_df[new_df['title']==movie].index[0]
    distance=similarity_score[index]
    recommend_movie=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    for i in recommend_movie:
        print(new_df.iloc[i[0]].title)

In [54]:
recommend("Pirates of the Caribbean: At World's End")

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
Life of Pi
Dallas Buyers Club

In [254]:
import pickle

In [255]:
pickle.dump(new_df.to_dict(),open('dict.pkl','wb'))

In [257]:
pickle.dump(similarity_score,open('similarity.pkl','wb'))

TypeError: Cannot index by location index with a non-integer key